### PR TITLE
Add accessibility support

### PR DESCRIPTION
**Pull request by TaehongKimKR**
I added accessibility support for VoiceOver.
It's a complete implementation of the accessibility protocol.
I hope this helps many blind people.

### CODE REVIEW

**Comment by slxl** [comment]
@TaehongKimKR thanks!
@HeshamMegid any chances this to be merged in near future?

**Comment by MacMark** [comment]
This would be great to have it released 👍

**Review by HeshamMegid — APPROVED** [review]

**Comment by HeshamMegid** [comment]
Thanks @TaehongKimKR!

**Comment by MacMark** [comment]
It works :-) Thanks to @TaehongKimKR and @HeshamMegid 

- In my podfile i added this like @HeshamMegid hinted to me:
    pod 'HMSegmentedControl', :git => 'https://github.com/HeshamMegid/HMSegmentedControl', :branch => 'master'
- pod install
- clean build folder
- Run and Accessibility Inspector gets infos about the segmented control

**Comment by Kros-s** [comment]
Does this require any setup, or should be added automatically, i'm not able to see any of the identifier for each segmented Element

**Pull request merged**
