### PR TITLE
fix bug for iOS10 show empty

### PR DESCRIPTION
**Pull request by waynett**

### CODE REVIEW

**Comment by wakingwwk** [comment]
if ([UIDevice currentDevice].systemVersion.floatValue <= 10.0 )  ???????

Why use '<=' instead of using  ‘ < ’ ?

**Comment by RAGOpoR** [comment]
when it going to merge ?

**Comment by sagiwei** [comment]
this need to be merged !

**Comment by geoffmacd** [comment]
yes merge please

**Comment by HeshamMegid** [comment]
@waynett Thanks for fixing that. I would like to solve this issue in a different way, as well as clean up the enlarged touch area property you added a bit, but I'm merging this for now till I have time to take another look at it.

In the mean time, check (and possibly contribute to) [HMSegmentedControl-Swift](https://github.com/HeshamMegid/HMSegmentedControl-Swift/).

**Comment by PasqualePuzio** [comment]
Is this fix already available on CocoaPods? I need to release an update for compatibility with iOS 10. Thanks

**Comment by PasqualePuzio** [comment]
Could you please create a tag and update the podspec file? Thanks

**Comment by InfAspire** [comment]
This fixed issues I was facing with missing titles in iOS 10. It would be great to update the podspec.

**Comment by HeshamMegid** [comment]
Check the 1.5.3 tag. I've also updated the podspec file.

**Comment by PasqualePuzio** [comment]
Thank you! Do you have any idea of how long it will take to have this release on CocoaPods? Thanks

**Comment by PasqualePuzio** [comment]
Hi, could you please upload the 1.5.3 tag to CocoaPods? Thanks

**Comment by PasqualePuzio** [comment]
Hi, sorry for being pushy but I really need to release an update of my app including this iOS 10 compatibility fix. Thank you!

**Comment by jojojames** [comment]
You could just patch the files manually yourself until then.

**Comment by PasqualePuzio** [comment]
@jojojames I probably will, but I'm asking because I know that pushing a release to CocoaPods takes not more than a couple of minutes. @HeshamMegid  Thank you for the great work btw! :)

**Comment by rabehssera** [comment]
I still don't see it on Cocoapods. Is that normal ?

**Comment by PasqualePuzio** [comment]
@rabehssera it's not, we're all waiting ;)

**Comment by yklishevich** [comment]
+1

**Comment by RAGOpoR** [comment]
we need it :)

**Comment by davroux** [comment]
+1

**Comment by Agoer** [comment]
prey~

**Comment by HeshamMegid** [comment]
I can see 1.5.3 on Cocoapods. Are you still having trouble installing it?

**Pull request merged**
