### PR TITLE
Additional property that allows positioning of image relative to text

### PR DESCRIPTION
**Pull request by lordzsolt**
Added imagePosition property. The image can be left, right, above, below or behind the text.
Both dynamic and fixed width is supported.

screen shot 2016-11-02 at 6 18 26 pm

screen shot 2016-11-02 at 6 19 29 pm

### CODE REVIEW

**Comment by HeshamMegid** [comment]
Thanks for the pull request and the awesome work! This version of HMSegmentedControl is currently in maintenance mode, so I'm only merging bug-fix pull requests, not new features. Feel free to contribute to the brand new [Swift version](https://github.com/HeshamMegid/HMSegmentedControl-Swift).

**Comment by gautamjain987** [comment]
I don't get it. It's such a useful feature. I would love to see it get merged. 

Also, there's a bug fix for text and image overlapping, which you've reverted. Any reason why ? 
@HeshamMegid

**Comment by sara-shokry** [comment]
this is really useful feature , hope to be merged soon

**Comment by HeshamMegid** [comment]
Okay, let's merge this!

I would be grateful if you update the branch to the latest version of master to be able to merge it.

**Comment by lordzsolt** [comment]
Should be up to date now :)

**Comment by HeshamMegid** [comment]
@lordzsolt awesome, thanks.

**Pull request merged**
